name: osu-profile
description: Inject information about your osu! profile into your readme!
author: newtykins

inputs:
  profile-id:
    description: 'The ID of the osu! profile to track'
    required: true
  api-key:
    description: 'Your osu! API key'
    required: true
  game-mode:
    description: 'osu! game mode to track'
    default: osu
  file-path:
    description: 'Path to the file to update'
  token:
    description: 'The GitHub token to use for manipulating the repository.'
    required: true
    default: ${{ github.token }}

runs:
  using: node20
  main: dist/index.js

branding:
  icon: 'activity'
  color: 'purple'
