name: osu-profile
description: inject information about your osu! profile into your readme!
author: newt

inputs:
  allowed-files:
    description: List of allowed file patterns (comma-separated)
    required: false
    default: '*.md'
    
runs:
  using: node20
  main: dist/index.js

branding:
  icon: 'activity'
  color: 'purple'
