name: osu-profile
description: inject information about your osu! profile into your readme!
author: newt

inputs:
  github-token:
    description: GitHub token with read/write permissions
    required: true
    default: ${{ github.token }}

  allowed-files:
    description: List of allowed file patterns (comma-separated)
    required: false
    default: "*.md"

  timezone:
    description: Timezone to use for the update timestamps.
    required: false
    default: "UTC"

runs:
  using: node20
  main: dist/index.js

branding:
  icon: "activity"
  color: "purple"
