name: update example

on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  readme:
    name: update osu!profile example
    runs-on: ubuntu-latest
    steps:
      - uses: isitreallyalive/osu-profile@main
        with:
          allowed-files: "example.md"